# Generated by Django 4.2.30 on 2026-07-04 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='課題タイトル')),
                ('raw_memo', models.TextField(verbose_name='違和感メモ')),
                ('category', models.CharField(blank=True, max_length=60, verbose_name='カテゴリ')),
                ('status', models.CharField(choices=[('unexplored', 'MVP未作成'), ('research', '研究候補'), ('implementing', '実装中'), ('implemented', '実装済み'), ('business', '事業化候補')], default='unexplored', max_length=20, verbose_name='ステータス')),
                ('target_user', models.CharField(blank=True, max_length=160, verbose_name='対象ユーザー')),
                ('core_problem', models.TextField(blank=True, verbose_name='本質的課題')),
                ('mvp_plan', models.TextField(blank=True, verbose_name='MVP案')),
                ('research_theme', models.TextField(blank=True, verbose_name='研究テーマ候補')),
                ('business_potential', models.TextField(blank=True, verbose_name='事業化可能性')),
                ('structured_data', models.JSONField(blank=True, default=dict, verbose_name='AI構造化データ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '課題アイデア',
                'verbose_name_plural': '課題アイデア',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'ユーザー'), ('assistant', 'AI')], max_length=20, verbose_name='発言者')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='problems.problemidea')),
            ],
            options={
                'verbose_name': '会話メッセージ',
                'verbose_name_plural': '会話メッセージ',
                'ordering': ['created_at'],
            },
        ),
    ]
