# Generated by Django 4.2.30 on 2026-07-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemidea',
            name='mvp_plan',
            field=models.TextField(blank=True, verbose_name='最初の試作品案'),
        ),
        migrations.AlterField(
            model_name='problemidea',
            name='status',
            field=models.CharField(choices=[('unexplored', '試作品未作成'), ('research', '研究候補'), ('implementing', '実装中'), ('implemented', '実装済み'), ('business', '事業化候補')], default='unexplored', max_length=20, verbose_name='ステータス'),
        ),
    ]
